version: "3.9"

services: 
    web:
        # build: ./web
        image: ildug/webserver-php:8.0-apache
        ports:
            - 8080:80
        environment:
            FQDN: my.dag.lan
            AUTH_SERVER_HOST: "https://auth/"
            DBHOST: "api" 
            DBNAME: "mydatabase" 
        volumes:
            - ./:/app





    